name: Auto Clean

on:
  workflow_dispatch:
  pull_request:
    branches:
      - "!main"
  schedule:
    # 北京时间每周一早上10点执行
    - cron: "0 2 * * 1"

permissions:
  contents: write

jobs:
  clean:
    runs-on: ubuntu-latest
    steps:
      - name: Delete older releases
        uses: dev-drprasad/delete-older-releases@v0.3.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # 仅保留最近的 3 个 Release
          keep_latest: 3
          # 同时删除关联的 Tag
          delete_tags: true
