name: Publish Extension

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
  push:
    branches:
      - main
    paths:
      - "package.json"
      - "package-lock.json"
  workflow_dispatch:
    inputs:
      publish_target:
        description: "Select the target to publish"
        required: true
        default: "both"
        type: choice
        options:
          - vscode
          - ovsx
          - release
          - both

permissions:
  contents: write

jobs:
  release:
    if: contains(github.event.inputs.publish_target, 'release') || contains(github.event.inputs.publish_target, 'both') || github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          cache: "npm"
      - run: npm ci
      - run: |
          npm run build:local
      - name: Get Package Version
        id: get_version
        run: |
          VERSION=$(npm pkg get version | tr -d '"')
          echo "VERSION_OUTPUT=$VERSION" >> $GITHUB_OUTPUT
      - name: Push Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: Release ${{ steps.get_version.outputs.VERSION_OUTPUT }}
          files: |
            vscode-rust-pack-*.vsix
          body_path: ${{ github.workspace }}/CHANGELOG.md
          draft: false
          prerelease: false
          tag_name: v${{ steps.get_version.outputs.VERSION_OUTPUT }}

  publish-VSCode:
    if: contains(github.event.inputs.publish_target, 'vscode') || contains(github.event.inputs.publish_target, 'both') || github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          cache: "npm"
      - run: npm ci
      - name: Publish to VSCode Marketplace
        if: success()
        env:
          VSCE_PAT: ${{ secrets.AZURE_TOKEN }}
        run: |
          npx @vscode/vsce publish

  publish-OVSX:
    if: contains(github.event.inputs.publish_target, 'ovsx') || contains(github.event.inputs.publish_target, 'both') || github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          cache: "npm"
      - run: npm ci
      - name: Publish to Open VSX Registry
        if: success()
        env:
          OVSX_PAT: ${{ secrets.OVSX_TOKEN }}
        run: |
          npx ovsx publish
