name: Publish Extension

on:
  pull_request:
    branches:
      - "!main"
  schedule:
    # 北京时间每周一早上12点执行
    - cron: "0 4 * * 1"
  workflow_dispatch:
    inputs:
      publish_target:
        description: "Select the target to publish"
        required: true
        default: "both"
        type: choice
        options:
          - vscode
          - ovsx
          - both

permissions:
  contents: write

jobs:
  publish-VSCode:
    if: contains(github.event.inputs.publish_target, 'vscode') || contains(github.event.inputs.publish_target, 'both') || github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          cache: "npm"
      - run: npm ci
      - name: Publish to VSCode Marketplace
        if: success()
        env:
          VSCE_PAT: ${{ secrets.AZURE_TOKEN }}
        run: |
          npx @vscode/vsce publish

  publish-OVSX:
    if: contains(github.event.inputs.publish_target, 'ovsx') || contains(github.event.inputs.publish_target, 'both') || github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          cache: "npm"
      - run: npm ci
      - name: Publish to Open VSX Registry
        if: success()
        env:
          OVSX_PAT: ${{ secrets.OVSX_TOKEN }}
        run: |
          npx ovsx publish
